### ISSUE TITLE
sfdisk: unrecognized option '--in-order'

### ISSUE THREAD

**Issue by JunhongXu** [tizen-artik/sdboot#3]
when i tried to followed this link:https://wiki.tizen.org/wiki/Booting_Tizen_3.0_From_microSD_On_ARTIK to flash Tizen into SD Card in "Format your microSD" step, I got an error: sfdisk: unrecognized option '--in-order'.

Here is the full trace:

 === Start /dev/sdb format === 
7386
========================================
Label          dev           size
========================================
boot		 /dev/sdb1  	 32 MB
modules		 /dev/sdb2  	 32 MB
rootfs		 /dev/sdb3  	 2048 MB
[Extend]	 /dev/sdb4
 system-data	 /dev/sdb5  	 256 MB
 user		 /dev/sdb6  	 5014 MB
Remove partition table...
1+0 records in
1+0 records out
512 bytes copied, 0.00143832 s, 356 kB/s
sfdisk: unrecognized option '--in-order'

Usage:
 sfdisk [options] <dev> [[-N] <part>]
 sfdisk [options] <command>

Display or manipulate a disk partition table.

Commands:
 -A, --activate <dev> [<part> ...] list or set bootable MBR partitions
 -d, --dump <dev>                  dump partition table (usable for later input)
 -J, --json <dev>                  dump partition table in JSON format
 -g, --show-geometry [<dev> ...]   list geometry of all or specified devices
 -l, --list [<dev> ...]            list partitions of each device
 -F, --list-free [<dev> ...]       list unpartitions free areas of each device
 -s, --show-size [<dev> ...]       list sizes of all or specified devices
 -T, --list-types                  print the recognized types (see -X)
 -V, --verify [<dev> ...]          test whether partitions seem correct

 --part-label <dev> <part> [<str>] print or change partition label
 --part-type <dev> <part> [<type>] print or change partition type
 --part-uuid <dev> <part> [<uuid>] print or change partition uuid
 --part-attrs <dev> <part> [<str>] print or change partition attributes

 <dev>                     device (usually disk) path
 <part>                    partition number
 <type>                    partition type, GUID for GPT, hex for MBR

Options:
 -a, --append              append partitions to existing partition table
 -b, --backup              backup partition table sectors (see -O)
     --bytes               print SIZE in bytes rather than in human readable format
 -f, --force               disable all consistency checking
     --color[=<when>]      colorize output (auto, always or never)
                             colors are enabled by default
 -N, --partno <num>        specify partition number
 -n, --no-act              do everything except write to device
     --no-reread           do not check whether the device is in use
 -O, --backup-file <path>  override default backup file name
 -o, --output <list>       output columns
 -q, --quiet               suppress extra info messages
 -X, --label <name>        specify label type (dos, gpt, ...)
 -Y, --label-nested <name> specify nested label type (dos, bsd)

 -L, --Linux               deprecated, only for backward compatibility
 -u, --unit S              deprecated, only sector unit is supported

 -h, --help     display this help and exit
 -v, --version  output version information and exit

Available columns (for -o):
 gpt: Device Start End Sectors Size Type Type-UUID Attrs Name UUID
 dos: Device Start End Sectors Cylinders Size Type Id Attrs Boot End-C/H/S
      Start-C/H/S
 bsd: Slice Start End Sectors Cylinders Size Type Bsize Cpg Fsize
 sgi: Device Start End Sectors Cylinders Size Type Id Attrs
 sun: Device Start End Sectors Cylinders Size Type Id Flags

For more details see sfdisk(8).

**Comment by amistewicz** [comment]
The problem is caused by a new version of `util-linux` package that provides `sfdisk` program. In version 2.26 and higher `--in-order` is removed. New version is shipped with Ubuntu 16.04.
There are other options that changed too.

Current workaround is to use old version of a `util-linux` package.

**Comment by jinocho00** [comment]
I submitted a new patch on this issue.
