### ISSUE TITLE
parallel flash support

### ISSUE THREAD

**Issue by amistewicz** [tizen-artik/sdboot#4]
Currently `TARGET_DIR` is set to `$BUILD_DIR/$MODEL` where `BUILD_DIR` is set to `pwd`.
It results in file conflicts when the `mk_sdboot.sh` script is called for the same artik model more than once.

Preferable solution is to use `mktemp -d` for `TARGET_DIR` and set `BUILD_DIR` to the actual script path not `pwd` so that the `mk_sdboot.sh` could be called from any location.

**Comment by jinocho00** [comment]
Good point. I will fix it according to your advice.

**Comment by jinocho00** [comment]
I submitted a new patch on this issue.
